# Generated by Django 4.0.2 on 2022-02-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_label_delete_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category_name']},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-label']},
        ),
    ]
