# Generated by Django 4.0.2 on 2022-02-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_rename_label_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_authors', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('published_date', models.CharField(max_length=50)),
                ('ISSN', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=20)),
                ('DOI', models.CharField(max_length=50)),
            ],
        ),
    ]
